## Assignment 1 ML (Sarthak Narang , COE 19 , Roll No-102003627)

In [2]:
import numpy as np

# Q1

In [3]:
# Q1a
array1a = np.array([1,2,3,6,4,5])
print(array1a)

#method1
reverse1=array1a[::-1]
print("reversed",reverse1)

#method2
reverse2=np.flipud(array1a)
print("reversed",reverse2)

[1 2 3 6 4 5]
reversed [5 4 6 3 2 1]
reversed [5 4 6 3 2 1]


In [5]:
# Q1b
array1b = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(array1b)

#method1
flatten_array=array1b.flatten()
print("\nflattened",flatten_array)

#method2
concatenated_array=np.concatenate(array1b)
print("\nflattened",concatenated_array)

[[1 2 3]
 [2 4 5]
 [1 2 3]]

flattened [1 2 3 2 4 5 1 2 3]

flattened [1 2 3 2 4 5 1 2 3]


In [5]:
# 1c
arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[1, 2], [3, 4]])
print(np.array_equal(arr1, arr2)) 

comparison_array=(arr1==arr2) #(True,True) will be in comparison
is_equal=comparison_array.all() # .all() checks if all element of list are true and if yes , then it gives true
print(is_equal)

True
True


In [6]:
# Q1d
x = np.array([1,2,3,4,5,1,2,1,1,1])
print(x)
valuex=np.bincount(x).argmax()
print(f'value = {valuex}' ) 
print(f'Index = {np.where(x==valuex)}')


y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
print(y)
valuey=np.bincount(y).argmax()
print(f'value = {valuey}') 
print(f'Index = {np.where(y==valuey)}')

[1 2 3 4 5 1 2 1 1 1]
value = 1
Index = (array([0, 5, 7, 8, 9], dtype=int64),)
[1 1 1 2 3 4 2 4 3 3]
value = 1
Index = (array([0, 1, 2], dtype=int64),)


In [8]:
# Q1e
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(gfg,"\n")
sum_of_all=gfg.sum()
sum_row_wise=gfg.sum(axis=0)
sum_collumn_wise=gfg.sum(axis=1)

print("sum_of_all\n",sum_of_all)

print("sum_row_wise\n",sum_row_wise)

print("sum_collumn_wise\n",sum_collumn_wise)

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]] 

sum_of_all
 45
sum_row_wise
 [[20  9 16]]
sum_collumn_wise
 [[14]
 [16]
 [15]]


In [8]:
# Q1f
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
sdiag = np.trace(n_array)
print(f'sum of diagnol elements is {sdiag}\n')

w, v = np.linalg.eig(n_array)
print(f'eigen values are\n{w}\n')
print(f'eigen vectors are\n {v}\n')

print (f'inverse of matrix\n{np.linalg.inv(n_array)}\n')
print (f'determinant = {np.linalg.det(n_array)}\n')

sum of diagnol elements is 176

eigen values are
[98.16835147 28.097044   49.73460452]

eigen vectors are
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]

inverse of matrix
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]

determinant = 137180.0000000001



In [9]:
# Q1g
p=np.array([[1,2],[2,3]])
q=np.array([[4,5],[6,7]])

mres=np.dot(p,q)
print(f'multiplication = \n{mres}\n')
cres=np.cov(p,q)
print(f'covariance=\n{cres}\n')


r=np.array([[1,2],[2,3],[4,5]])
s=np.array([[4,5,1],[6,7,2]])

mres2=np.dot(r,s)
print(f'multiplication2 = \n{mres2}\n')
cres2=np.cov(r,s.T)
print(f'covariance2 =\n{cres2}')



multiplication = 
[[16 19]
 [26 31]]

covariance=
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]

multiplication2 = 
[[16 19  5]
 [26 31  8]
 [46 55 14]]

covariance2 =
[[0.5 0.5 0.5 1.  1.  0.5]
 [0.5 0.5 0.5 1.  1.  0.5]
 [0.5 0.5 0.5 1.  1.  0.5]
 [1.  1.  1.  2.  2.  1. ]
 [1.  1.  1.  2.  2.  1. ]
 [0.5 0.5 0.5 1.  1.  0.5]]


In [10]:
# Q1h
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner= np.inner(x,y)
print(f'inner product\n {inner} \n')
outer=np.outer(x,y)
print(f'outer product\n {outer}\n')
cartesian=np.cross(x,y)
print(f'cartesian product\n {cartesian}')


inner product
 [[17 52]
 [13 62]] 

outer product
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

cartesian product
 [[-20   4   7]
 [-84  36  20]]


## Q2

In [9]:
# Q2a
array2 = np.array([[1, -2, 3],[-4, 5, -6]])
print("given\n",array2,"\n")
#(i)
abso=np.absolute(array2)
print(f'element wise absolute:\n{abso}\n')

#(ii)
flat2=array2.flatten()
print(f'25 percentile of flattened-> {np.percentile(flat2,25)}')
print(f'50 percentile of flattened-> {np.percentile(flat2,50)}')
print(f'75 percentile of flattened-> {np.percentile(flat2,75)}\n')

print(f'25 percentile of row-> {np.percentile(array2,25,axis=0)}')
print(f'50 percentile of row-> {np.percentile(array2,50,axis=0)}')
print(f'75 percentile of row-> {np.percentile(array2,75,axis=0)}\n')

print(f'25 percentile of column-> {np.percentile(array2,25,axis=1)}')
print(f'50 percentile of column-> {np.percentile(array2,50,axis=1)}')
print(f'75 percentile of column-> {np.percentile(array2,75,axis=1)}\n')

#(iii)
print("flatten mean is",np.mean(flat2))
print("column-wise mean is",np.mean(array2,axis=1))
print("row-wise mean is",np.mean(array2,axis=0),"\n")

print("flatten median is",np.median(flat2))
print("column-wise median is",np.median(array2,axis=1))
print("row-wise median is",np.median(array2,axis=0),"\n")

print("flatten std is",np.std(flat2))
print("column-wise std is",np.std(array2,axis=1))
print("row-wise std is",np.std(array2,axis=0))

given
 [[ 1 -2  3]
 [-4  5 -6]] 

element wise absolute:
[[1 2 3]
 [4 5 6]]

25 percentile of flattened-> -3.5
50 percentile of flattened-> -0.5
75 percentile of flattened-> 2.5

25 percentile of row-> [-2.75 -0.25 -3.75]
50 percentile of row-> [-1.5  1.5 -1.5]
75 percentile of row-> [-0.25  3.25  0.75]

25 percentile of column-> [-0.5 -5. ]
50 percentile of column-> [ 1. -4.]
75 percentile of column-> [2.  0.5]

flatten mean is -0.5
column-wise mean is [ 0.66666667 -1.66666667]
row-wise mean is [-1.5  1.5 -1.5] 

flatten median is -0.5
column-wise median is [ 1. -4.]
row-wise median is [-1.5  1.5 -1.5] 

flatten std is 3.8622100754188224
column-wise std is [2.05480467 4.78423336]
row-wise std is [2.5 3.5 4.5]


In [10]:
# Q2b
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print("floored values  ",np.floor(a))
print("ceiling values  ",np.ceil(a))
print("truncated values",np.trunc(a))
print("rounded values  ",np.round(a))

floored values   [-2. -2. -1.  0.  1.  1.  3.]
ceiling values   [-1. -1. -0.  1.  2.  2.  3.]
truncated values [-1. -1. -0.  0.  1.  1.  3.]
rounded values   [-2. -2. -0.  0.  2.  2.  3.]


## Q3

In [11]:
# Q3a
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("array-",array)

sortedarray=np.sort(array)
print("sorted-",sortedarray)

indices = np.argsort(array)
print("indices-" ,indices)

print("4 smallest-",sortedarray[0:4])

print("5 largest-",sortedarray[-5:])

array- [ 10  52  62  16  16  54 453]
sorted- [ 10  16  16  52  54  62 453]
indices- [0 3 4 1 5 2 6]
4 smallest- [10 16 16 52]
5 largest- [ 16  52  54  62 453]


In [12]:
# Q3b
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print("integral values ",array[array == array.astype(int)])
print("float values ",array[array != array.astype(int)])

integral values  [1. 2. 3. 2.]
float values  [1.2 2.2]


## Q4

In [15]:
from PIL import Image
import numpy as np
def img_to_array(path):
    img = np.array(Image.open(path))
    print(img)
    print(type(img))
    print(img.dtype)
    print(img.shape)
    file = open("file1.txt", "w+")
    content = str(img)
    file.write(content)
    file.close()

img_to_array('image.jpg')
 
# q4b Displaying the contents of the text file
file = open("file1.txt", "r")
content = file.read()
print("\nContent of file1.txt:\n", content)
file.close()

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
<class 'numpy.ndarray'>
uint8
(471, 688, 3)

Content of file1.txt:
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 2

## End Of File